--- 
id: tokenCourse
name: 02 ERC20トークン
summary: Solidity Beginner Course based on the popular https://solidity-by-example.org/ contracts. Developed by the p2p learning platform https://dacade.org.
level: 2
tags: 
  - Solidity
  - Tokens
  - ERC20
steps:
  - name: 1. 概要
    path: introduction
  - name: 2. インターフェース
    path: erc20-interface
  - name: 3. トークンの作成
    path: erc20-token-creation
  - name: 4. トークンの操作
    path: erc20-interaction
