--- 
id: soliditybeginner
name: 01 Solidity文法基礎
summary: Solidity Beginner Course based on the popular https://solidity-by-example.org/ contracts. Developed by the p2p learning platform https://dacade.org.
level: 1
tags: 
  - Solidity
steps:
  - name: 1. 基本レイアウト
    path: 1_basic-layout
