--- 
id: soliditybeginner
name: 01 Solidity文法基礎
summary: Solidity Beginner Course based on the popular https://solidity-by-example.org/ contracts. Developed by the p2p learning platform https://dacade.org.
level: 1
tags: 
  - Solidity
steps:
  - name: 1. 基本レイアウト
    path: 1_basic-layout
  - name: 2. 変数型
    path: 2_data-types
  - name: 3. 変数タイプ
    path: 3_variable-type
  - name: 4. 変数の宣言と可視性
    path: 4_visibility
  - name: 5. 構造体
    path: 5_structs
  - name: 6 配列
    path: 6_arrays
  - name: 7 列挙型
    path: 7_enums
  - name: 8 マッピング
    path: 8_mappings
  - name: 9 制御構文 IF文
    path: 9_if-else
  - name: 10 繰り返し構文 for、while文
    path: 10_loops


